name: CI of mc_mujoco

on:
  repository_dispatch:
    types:
    - run-ci
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    # Run on Sunday, Tuesday and Thursday nights
    - cron: '0 23 * * 0,1,4'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        compiler: [gcc]
        build-type: [RelWithDebInfo]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: libmc-rtc-dev libxi-dev libxcursor-dev libxkbcommon-dev libxinerama-dev libxrandr-dev libglew-dev libboost-program-options-dev
          apt-mirrors:
            mc-rtc:
              cloudsmith: mc-rtc/head
        macos: |
          brew-taps: mc-rtc/mc-rtc
          brew: mc_rtc
        windows: |
          vcpkg:
            repo: microsoft/vcpkg
            owner: mc-rtc
            token: "${{ secrets.GITHUB_TOKEN }}"
            registries:
            - repo: mc-rtc/vcpkg-registry
              packages: [ spacevecalg, rbdyn, eigen-qld, sch-core, tasks, mc-rbdyn-urdf, mc-rtc-data, eigen-quadprog, state-observation, hpp-spline, mc-rtc ]
    - name: Install MuJoCo
      shell: bash
      run: |
        set -x
        set -e
        mkdir -p /opt
        cd /opt
        MUJOCO_VERSION=2.3.1
        wget --quiet https://github.com/deepmind/mujoco/releases/download/${MUJOCO_VERSION}/mujoco-${MUJOCO_VERSION}-linux-x86_64.tar.gz
        tar xzf mujoco-${MUJOCO_VERSION}-linux-x86_64.tar.gz
        mv mujoco-${MUJOCO_VERSION} mujoco
        rm -rf *.tar.gz
        echo "MUJOCO_ROOT_DIR=/opt/mujoco" >> $GITHUB_ENV
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        options: -DMUJOCO_ROOT_DIR="${{ env.MUJOCO_ROOT_DIR }}"
    - name: Check usage
      shell: bash
      run: |
        set -x
        cd .github/workflows/test-standalone
        mkdir build && cd build
        cmake ../ -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
        cmake --build . --config ${{ matrix.build-type }}
        ctest -V -C ${{ matrix.build-type }}
